# -*- coding: utf-8 -*-
"""miniChess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cPaNpGpBXGA0KZiEXPg0wWuFAsN128sl

JePyChess
=========

Introducing "JeffProd Simple Python Chess Program" running in command line.
You can play a full game versus it.
Run it with the command : ./main.py

It supports actually :
- promote
- under-promote
- capture "en passant"

Commands are :
- **new** to start a new game
- **e2e4** or **e7e8q** for example to move a piece. Promotes are q,r,n,b for queen, rook, knight, bishop
- **undomove** to cancel the last move
- **legalmoves** to show legal moves for side to move
- **go** requests the engine to play now
- **setboard fen** to set the board as the FEN position given
- **getboard** to export the current FEN position
- **sd x** to set the depth search
- **perft x** to test the move generator (x = search depth)
- **quit**... to quit

Things to do :
- move ordering
- quiescent search
- 50 moves rule
- 3 repetitions rule
- time settings
- opening book

Requirements :
- Python 3

More information on :
https://fr.jeffprod.com/blog/2014/comment-programmer-un-jeu-dechecs/

#Piece
"""

class Piece:

    "Chess set class"

    VIDE='.' # empty piece name (=empty square '.' in console)

    # Name of the pieces
    nomPiece=(VIDE,'ROI','DAME','TOUR','CAVALIER','FOU','PION')

    # Give a score value for each piece : KING=0, QUEEN=9, ROOK=5...
    valeurPiece=(0,0,9,5,3,3,1)

    # For the pieces moves, using method "mail box" from Robert Hyatt
    # It helps to know if a piece is not moved outside the board !
    tab120 = (
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
	-1,  0,  1,  2,  3,  4,  5,  6,  7, -1,
	-1,  8,  9, 10, 11, 12, 13, 14, 15, -1,
	-1, 16, 17, 18, 19, 20, 21, 22, 23, -1,
	-1, 24, 25, 26, 27, 28, 29, 30, 31, -1,
	-1, 32, 33, 34, 35, 36, 37, 38, 39, -1,
	-1, 40, 41, 42, 43, 44, 45, 46, 47, -1,
	-1, 48, 49, 50, 51, 52, 53, 54, 55, -1,
	-1, 56, 57, 58, 59, 60, 61, 62, 63, -1,
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1
	)
    tab64 = (
	21, 22, 23, 24, 25, 26, 27, 28,
	31, 32, 33, 34, 35, 36, 37, 38,
	41, 42, 43, 44, 45, 46, 47, 48,
	51, 52, 53, 54, 55, 56, 57, 58,
	61, 62, 63, 64, 65, 66, 67, 68,
	71, 72, 73, 74, 75, 76, 77, 78,
	81, 82, 83, 84, 85, 86, 87, 88,
	91, 92, 93, 94, 95, 96, 97, 98
	)

    # Moving vectors according to the 'tab64',
    deplacements_tour=(-10,10,-1,1)
    deplacements_fou=(-11,-9,11,9)
    deplacements_cavalier=(-12,-21,-19,-8,12,21,19,8)
    # KING and QUEEN = BISHOP + ROOK !



    def __init__(self,nom=VIDE,couleur=''):

        """Creating a piece object, with its attributes :
        - 'nom' as name (ROI, DAME...);
        - 'couleur' as color (blanc,noir);
        - 'valeur' as its value"""

        self.nom=nom
        self.couleur=couleur
        self.valeur=self.valeurPiece[self.nomPiece.index(nom)]



    def isEmpty(self):

        """Returns TRUE or FALSE if this piece object is defined,
        As any square on board can have a piece on it, or not,
        we can set a null piece on a square."""

        return (self.nom==self.VIDE)



    def pos2_roi(self,pos1,cAd,echiquier,dontCallIsAttacked=False):

        """Returns the list of moves for the king :
        - which is at square 'pos1'
        - which opponent color is 'cAd' (blanc,noir)
        - dontCallIsAttacked is set to avoid recursives calls
        between is_attacked() and gen_moves_list().
        """

        liste=[]

        for i in (self.deplacements_tour+self.deplacements_fou):
            n=self.tab120[self.tab64[pos1]+i]
            if(n!=-1):
                if(echiquier.cases[n].isEmpty() or echiquier.cases[n].couleur==cAd):
                    liste.append((pos1,n,''))

        if(dontCallIsAttacked):
            return liste # we just wanted moves that can attack

        # The current side to move is the opposite of cAd
        c=echiquier.oppColor(cAd)

        # Castle moves
        if(c=='blanc'):
            if(echiquier.white_can_castle_63):
                # If a rook is at square 63
                # And if squares between KING and ROOK are empty
                # And if squares on which KING walks are not attacked
                # And if KING is not in check
                # Then we can add this castle move
                if(echiquier.cases[63].nom=='TOUR' and \
                echiquier.cases[63].couleur=='blanc' and \
                echiquier.cases[61].isEmpty() and \
                echiquier.cases[62].isEmpty() and \
                echiquier.is_attacked(61,'noir')==False and \
                echiquier.is_attacked(62,'noir')==False and \
                echiquier.is_attacked(pos1,'noir')==False):
                    liste.append((pos1,62,''))
            if(echiquier.white_can_castle_56):
                # S'il y a une tour en 56, etc...
                if(echiquier.cases[56].nom=='TOUR' and \
                echiquier.cases[56].couleur=='blanc' and \
                echiquier.cases[57].isEmpty() and \
                echiquier.cases[58].isEmpty() and \
                echiquier.cases[59].isEmpty() and \
                echiquier.is_attacked(58,cAd)==False and \
                echiquier.is_attacked(59,cAd)==False and \
                echiquier.is_attacked(pos1,cAd)==False):
                    liste.append((pos1,58,''))
        elif(c=='noir'):
            if(echiquier.black_can_castle_7):
                if(echiquier.cases[7].nom=='TOUR' and \
                echiquier.cases[7].couleur=='noir' and \
                echiquier.cases[5].isEmpty() and \
                echiquier.cases[6].isEmpty() and \
                echiquier.is_attacked(5,cAd)==False and \
                echiquier.is_attacked(6,cAd)==False and \
                echiquier.is_attacked(pos1,cAd)==False):
                    liste.append((pos1,6,''))
            if(echiquier.black_can_castle_0):
                if(echiquier.cases[0].nom=='TOUR' and \
                echiquier.cases[0].couleur=='noir' and \
                echiquier.cases[1].isEmpty() and \
                echiquier.cases[2].isEmpty() and \
                echiquier.cases[3].isEmpty() and \
                echiquier.is_attacked(2,cAd)==False and \
                echiquier.is_attacked(3,cAd)==False and \
                echiquier.is_attacked(pos1,cAd)==False):
                    liste.append((pos1,2,''))

        return liste



    def pos2_tour(self,pos1,cAd,echiquier):

        """Returns the list of moves for a ROOK :
        - at square number 'pos1' (0 to 63)
        - opponent color is cAd (blanc,noir)"""

        liste=[]

        for k in self.deplacements_tour:
            j=1
            while(True):
                n=self.tab120[self.tab64[pos1] + (k * j)]
                if(n!=-1): # as we are not out of the board
                    if(echiquier.cases[n].isEmpty() or echiquier.cases[n].couleur==cAd):
                        liste.append((pos1,n,'')) # append the move if square is empty of opponent color
                else:
                    break # stop if outside of the board
                if(not echiquier.cases[n].isEmpty()):
                    break # destination square is not empty (opponent or not) then the rook won't pass through
                j=j+1

        return liste



    def pos2_cavalier(self,pos1,cAd,echiquier):

        """Returns the list of moves for a KNIGHT :
        - at square number 'pos1' (0 to 63)
        - opponent color is cAd (blanc,noir)"""

        liste=[]

        for i in self.deplacements_cavalier:
            n=self.tab120[self.tab64[pos1]+i]
            if(n!=-1):
                if(echiquier.cases[n].isEmpty() or echiquier.cases[n].couleur==cAd):
                    liste.append((pos1,n,''))

        return liste



    def pos2_fou(self,pos1,cAd,echiquier):

        """Returns the list of moves for a BISHOP :
        - at square number 'pos1' (0 to 63)
        - opponent color is cAd (blanc,noir)"""

        liste=[]

        for k in self.deplacements_fou:
            j=1
            while(True):
                n=self.tab120[self.tab64[pos1] + (k * j)]
                if(n!=-1): # as we are not out of the board
                    if(echiquier.cases[n].isEmpty() or echiquier.cases[n].couleur==cAd):
                        liste.append((pos1,n,'')) # append the move if square is empty of opponent color
                else:
                    break # stop if outside of the board
                if(not echiquier.cases[n].isEmpty()):
                    break # destination square is not empty (opponent or not) then the bishop won't pass through
                j=j+1

        return liste



    def pos2_pion(self,pos1,couleur,echiquier):

        """Returns the list of moves for a PAWN :
        - at square number 'pos1' (0 to 63)
        - opponent color is cAd (blanc,noir)"""

        liste=[]

        # White PAWN ---------------------------------------------------
        if(couleur=='blanc'):

            # Upper square
            n=self.tab120[self.tab64[pos1]-10]
            if(n!=-1):
                if(echiquier.cases[n].isEmpty()):
                    # If the PAWN has arrived to rank 8 (square 0 to 7),
                    if(n<8):
                        # it will be promoted
                        liste.append((pos1,n,'q'))
                        liste.append((pos1,n,'r'))
                        liste.append((pos1,n,'n'))
                        liste.append((pos1,n,'b'))
                    else:
                        liste.append((pos1,n,''))

            # 2nd square if PAWN is at starting square
            if(echiquier.ROW(pos1)==6):
                # If the 2 upper squares are empty
                if(echiquier.cases[pos1-8].isEmpty() and echiquier.cases[pos1-16].isEmpty()):
                    liste.append((pos1,pos1-16,''))

            # Capture upper left
            n=self.tab120[self.tab64[pos1]-11]
            if(n!=-1):
                if(echiquier.cases[n].couleur=='noir' or echiquier.ep==n):
                    if(n<8): # Capture + promote
                        liste.append((pos1,n,'q'))
                        liste.append((pos1,n,'r'))
                        liste.append((pos1,n,'n'))
                        liste.append((pos1,n,'b'))
                    else:
                        liste.append((pos1,n,''))

            # Capture upper right
            n=self.tab120[self.tab64[pos1]-9]
            if(n!=-1):
                if(echiquier.cases[n].couleur=='noir' or echiquier.ep==n):
                    if(n<8):
                        liste.append((pos1,n,'q'))
                        liste.append((pos1,n,'r'))
                        liste.append((pos1,n,'n'))
                        liste.append((pos1,n,'b'))
                    else:
                        liste.append((pos1,n,''))

        # Black PAWN ---------------------------------------------------
        else:

            # Upper square
            n=self.tab120[self.tab64[pos1]+10]
            if(n!=-1):
                if(echiquier.cases[n].isEmpty()):
                    # PAWN has arrived to 8th rank (square 56 to 63),
                    # it will be promoted
                    if(n>55):
                        liste.append((pos1,n,'q'))
                        liste.append((pos1,n,'r'))
                        liste.append((pos1,n,'n'))
                        liste.append((pos1,n,'b'))
                    else:
                        liste.append((pos1,n,''))

            # 2nd square if PAWN is at starting square
            if(echiquier.ROW(pos1)==1):
                # If the 2 upper squares are empty
                if(echiquier.cases[pos1+8].isEmpty() and echiquier.cases[pos1+16].isEmpty()):
                    liste.append((pos1,pos1+16,''))

            # Capture bottom left
            n=self.tab120[self.tab64[pos1]+9]
            if(n!=-1):
                if(echiquier.cases[n].couleur=='blanc' or echiquier.ep==n):
                    if(n>55):
                        liste.append((pos1,n,'q'))
                        liste.append((pos1,n,'r'))
                        liste.append((pos1,n,'n'))
                        liste.append((pos1,n,'b'))
                    else:
                        liste.append((pos1,n,''))

            # Capture bottom right
            n=self.tab120[self.tab64[pos1]+11]
            if(n!=-1):
                if(echiquier.cases[n].couleur=='blanc' or echiquier.ep==n):
                    if(n>55):
                        liste.append((pos1,n,'q'))
                        liste.append((pos1,n,'r'))
                        liste.append((pos1,n,'n'))
                        liste.append((pos1,n,'b'))
                    else:
                        liste.append((pos1,n,''))

        return liste

"""#Board"""

from piece import *
import os # for clear ou cls

class Board:

    "The chess board"

    # Names of the 64 sqares
    coord=[
        'a8','b8','c8','d8','e8','f8','g8','h8',
        'a7','b7','c7','d7','e7','f7','g7','h7',
        'a6','b6','c6','d6','e6','f6','g6','h6',
        'a5','b5','c5','d5','e5','f5','g5','h5',
        'a4','b4','c4','d4','e4','f4','g4','h4',
        'a3','b3','c3','d3','e3','f3','g3','h3',
        'a2','b2','c2','d2','e2','f2','g2','h2',
        'a1','b1','c1','d1','e1','f1','g1','h1',
        ]



    def __init__(self):
        self.init()



    def init(self):

        "Init the chess board at starting position"

        # Chessboard has 64 squares, numbered from 0 to 63 (a8 to h1)
        # Placing pieces ('cases' is 'square' in french :)
        self.cases = [
            Piece('TOUR','noir'),Piece('CAVALIER','noir'),Piece('FOU','noir'),Piece('DAME','noir'),Piece('ROI','noir'),Piece('FOU','noir'),Piece('CAVALIER','noir'),Piece('TOUR','noir'),
            Piece('PION','noir'),Piece('PION','noir'),Piece('PION','noir'),Piece('PION','noir'),Piece('PION','noir'),Piece('PION','noir'),Piece('PION','noir'),Piece('PION','noir'),
            Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),
            Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),
            Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),
            Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),Piece(),
            Piece('PION','blanc'),Piece('PION','blanc'),Piece('PION','blanc'),Piece('PION','blanc'),Piece('PION','blanc'),Piece('PION','blanc'),Piece('PION','blanc'),Piece('PION','blanc'),
            Piece('TOUR','blanc'),Piece('CAVALIER','blanc'),Piece('FOU','blanc'),Piece('DAME','blanc'),Piece('ROI','blanc'),Piece('FOU','blanc'),Piece('CAVALIER','blanc'),Piece('TOUR','blanc')
            ]

        self.side2move='blanc'
        self.ep=-1 # the number of the square where to take 'en pasant'
        self.history=[] # the moves history
        self.ply=0 # half-move number since the start

        # Castle rights
        self.white_can_castle_56=True
        self.white_can_castle_63=True
        self.black_can_castle_0=True
        self.black_can_castle_7=True



    def gen_moves_list(self,color='',dontCallIsAttacked=False):

        """Returns all possible moves for the requested color.
        If color is not given, it is considered as the side to move.
        dontCallIsAttacked is a boolean flag to avoid recursive calls,
        due to the actually wrotten is_attacked() function calling
        this gen_moves_list() function.
        A move is defined as it :
        - the number of the starting square (pos1)
        - the number of the destination square (pos2)
        - the name of the piece to promote '','q','r','b','n'
          (queen, rook, bishop, knight)
        """

        if(color==''):
            color=self.side2move
        mList=[]

        # For each 'piece' on the board (pos1 = 0 to 63)
        for pos1,piece in enumerate(self.cases):

            # Piece (or empty square) color is not the wanted ? pass
            if piece.couleur!=color:
                continue

            if(piece.nom=='ROI'): # KING
                mList+=piece.pos2_roi(pos1,self.oppColor(color),self,dontCallIsAttacked)
                continue

            elif(piece.nom=='DAME'): # QUEEN = ROOK + BISHOP moves !
                mList+=piece.pos2_tour(pos1,self.oppColor(color),self)
                mList+=piece.pos2_fou(pos1,self.oppColor(color),self)
                continue

            elif(piece.nom=='TOUR'): # ROOK
                mList+=piece.pos2_tour(pos1,self.oppColor(color),self)
                continue

            elif(piece.nom=='CAVALIER'): # KNIGHT
                mList+=piece.pos2_cavalier(pos1,self.oppColor(color),self)
                continue

            elif(piece.nom=='FOU'): # BISHOP
                mList+=piece.pos2_fou(pos1,self.oppColor(color),self)
                continue

            if(piece.nom=='PION'): # PAWN
                mList+=piece.pos2_pion(pos1,piece.couleur,self)
                continue

        return mList



    def setboard(self,fen):

        """Set the board to the FEN position given. i.e. :
        rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - - 0
        Returns TRUE or FALSE if done or not.
        If not : print errors.
        """

        f=fen.split()
        err=""

        if(len(f)!=6):
            err+="Wrong FEN notation. It should be :\n"
            err+="[pieces] [side to move] [castle rights] [ep] [plys] [move number]\n"
            err+="i.e. : rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1\n"
            print(err)
            return False

        self.init()
        self.white_can_castle_56=False
        self.white_can_castle_63=False
        self.black_can_castle_0=False
        self.black_can_castle_7=False

        fen =   f[0] # rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR
        trait = f[1] # b ou w (black,white)
        roque = f[2] # KQkq
        ep =    f[3] # e3
        rule50= f[4] # 0 (half-moves since start of game for 50 moves rule)
        num =   f[5] # move number

        # Setting pieces
        i=0
        for c in fen:
            if(c=='k'):
                self.cases[i]=Piece('ROI','noir')
                i=i+1
            elif(c=='q'):
                self.cases[i]=Piece('DAME','noir')
                i=i+1
            elif(c=='r'):
                self.cases[i]=Piece('TOUR','noir')
                i=i+1
            elif(c=='n'):
                self.cases[i]=Piece('CAVALIER','noir')
                i=i+1
            elif(c=='b'):
                self.cases[i]=Piece('FOU','noir')
                i=i+1
            elif(c=='p'):
                self.cases[i]=Piece('PION','noir')
                i=i+1
            elif(c=='K'):
               self.cases[i]=Piece('ROI','blanc')
               i=i+1
            elif(c=='Q'):
               self.cases[i]=Piece('DAME','blanc')
               i=i+1
            elif(c=='R'):
                self.cases[i]=Piece('TOUR','blanc')
                i=i+1
            elif(c=='N'):
                self.cases[i]=Piece('CAVALIER','blanc')
                i=i+1
            elif(c=='B'):
                self.cases[i]=Piece('FOU','blanc')
                i=i+1
            elif(c=='P'):
                self.cases[i]=Piece('PION','blanc')
                i=i+1
            elif(c=='/'):
                pass
            else: # a number of empty squares is given
                try:
                    nb=int(c)
                except ValueError:
                    print('Error : wrong FEN. Integer expected.')
                    return
                cpt=0
                while(cpt<nb):
                    self.cases[i]=Piece()
                    cpt=cpt+1
                    i=i+1

        # Checking number of squares
        if(i!=64):
            print('Error : wrong FEN.')
            self.init()
            return False

        # Site to move
        if(trait=='b'):
            self.side2move='noir'
        else:
            self.side2move='blanc'

        # Castle rights
        if(roque!='-'):
            if('K' in roque):
                self.white_can_castle_63=True
            if('Q' in roque):
                self.white_can_castle_56=True
            if('k' in roque):
                self.black_can_castle_7=True
            if('q' in roque):
                self.black_can_castle_0=True

        # Prise "en passant"
        if(ep not in self.coord):
            self.ep=-1
        else:
            self.ep=self.coord.index(ep)

        # TODO
        # half-moves since start of game for 50 moves rule

        # TODO
        # move number

        return True



    def getboard(self):

        """Returns the FEN notation of the current board. i.e. :
        rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - - 0
        """

        emptySq=0 # couting empty squares
        s='' # constructring the FEN string

        # Parsing each board square (i = 0 to 63)
        for i,piece in enumerate(self.cases):

            p=piece.nom
            c=piece.couleur

            if(emptySq==8):
                s+='8'
                emptySq=0

            if(i and i%8==0):
                if(emptySq>0):
                    s+=str(emptySq)
                    emptySq=0
                s+='/'

            if(piece.isEmpty()):
                emptySq+=1

            elif(p=='ROI'):
                if(emptySq>0):
                    s+=str(emptySq)
                    emptySq=0
                if(c=='noir'):
                    s+='k'
                else:
                    s+='K'

            elif(p=='DAME'):
                if(emptySq>0):
                    s+=str(emptySq)
                    emptySq=0
                if(c=='noir'):
                    s+='q'
                else:
                    s+='Q'

            elif(p=='TOUR'):
                if(emptySq>0):
                    s+=str(emptySq)
                    emptySq=0
                if(c=='noir'):
                    s+='r'
                else:
                    s+='R'

            elif(p=='CAVALIER'):
                if(emptySq>0):
                    s+=str(emptySq)
                    emptySq=0
                if(c=='noir'):
                    s+='n'
                else:
                    s+='N'

            elif(p=='FOU'):
                if(emptySq>0):
                    s+=str(emptySq)
                    emptySq=0
                if(c=='noir'):
                    s+='b'
                else:
                    s+='B'

            elif(p=='PION'):
                if(emptySq>0):
                    s+=str(emptySq)
                    emptySq=0
                if(c=='noir'):
                    s+='p'
                else:
                    s+='P'

        if(emptySq>0):
            s+=str(emptySq)

        # b or w (black,white)
        if(self.side2move=='blanc'):
            s+=' w '
        else:
            s+=' b '

        # Castle rights (KQkq)
        no_castle_right=True
        if(self.white_can_castle_63):
            s+='K'
            no_castle_right=False
        if(self.white_can_castle_56):
            s+='Q'
            no_castle_right=False
        if(self.black_can_castle_7):
            s+='k'
            no_castle_right=False
        if(self.black_can_castle_0):
            s+='q'
            no_castle_right=False
        if(no_castle_right):
            s+='-'

        # prise en passant e3
        if(self.ep!=-1):
            s+=' '+self.coord[self.ep]
        else:
            s+=' -'

        # TODO
        # number of half-moves for 50 moves rule
        s+=' -'

        # numéro du coup
        s+=' '+str(int(len(self.history)/2))

        return s



    def domove(self,depart,arrivee,promote):

        """Move a piece on the board from the square numbers
        'depart' to 'arrivee' (0..63) respecting rules :
        - prise en passant
        - promote and under-promote
        - castle rights
        Returns :
        - TRUE if the move do not let king in check
        - FALSE otherwise and undomove is done.
        """

        # Debugging tests
        #if(self.cases[depart].isEmpty()):
        #    print('domove() ERROR : asked for an empty square move : ',depart,arrivee,promote)
        #    return
        #if(int(depart)<0 or int(depart)>63):
        #    print('domove() ERROR : incorrect FROM square number : ',depart)
        #    return
        #if(int(arrivee)<0 or int(arrivee)>63):
        #    print('domove() ERROR : incorrect TO square number : ',arrivee)
        #    return
        #if(not(promote=='' or promote=='q' or promote=='r' or promote=='n' or promote=='b')):
        #    print('domove() ERROR : incorrect promote : ',promote)
        #    return

		# Informations to save in the history moves
        pieceDeplacee=self.cases[depart] # moved piece
        piecePrise=self.cases[arrivee] # taken piece, can be null : Piece()
        isEp=False # will be used to undo a ep move
        histEp=self.ep # saving the actual ep square (-1 or square number TO)
        hist_roque_56=self.white_can_castle_56
        hist_roque_63=self.white_can_castle_63
        hist_roque_0=self.black_can_castle_0
        hist_roque_7=self.black_can_castle_7
        flagViderEp=True # flag to erase ep or not : if the pawn moved is not taken directly, it can't be taken later

        # Moving piece
        self.cases[arrivee]=self.cases[depart]
        self.cases[depart]=Piece()

        self.ply+=1

        # a PAWN has been moved -------------------------------------
        if(pieceDeplacee.nom=='PION'):

            # White PAWN
            if(pieceDeplacee.couleur=='blanc'):

                # If the move is "en passant"
                if(self.ep==arrivee):
                    piecePrise=self.cases[arrivee+8] # take black pawn
                    self.cases[arrivee+8]=Piece()
                    isEp=True

                # The white pawn moves 2 squares from starting square
                # then blacks can take "en passant" next move
                elif(self.ROW(depart)==6 and self.ROW(arrivee)==4):
                    self.ep=arrivee+8
                    flagViderEp=False

            # Black PAWN
            else:

                if(self.ep==arrivee):
                    piecePrise=self.cases[arrivee-8]
                    self.cases[arrivee-8]=Piece()
                    isEp=True

                elif(self.ROW(depart)==1 and self.ROW(arrivee)==3):
                    self.ep=arrivee-8
                    flagViderEp=False

        # a ROOK has been moved--------------------------------------
        # update castle rights

        elif(pieceDeplacee.nom=='TOUR'):

            # White ROOK
            if(pieceDeplacee.couleur=='blanc'):
                if(depart==56):
                    self.white_can_castle_56=False
                elif(depart==63):
                    self.white_can_castle_63=False

            # Black ROOK
            else:
                if(depart==0):
                    self.black_can_castle_0=False
                elif(depart==7):
                    self.black_can_castle_7=False

        # a KING has been moved-----------------------------------------

        elif(pieceDeplacee.nom=='ROI'):

            # White KING
            if(pieceDeplacee.couleur=='blanc'):

                # moving from starting square
                if(depart==60):
                    # update castle rights
                    self.white_can_castle_56=False
                    self.white_can_castle_63=False

                    # If castling, move the rook
                    if(arrivee==58):
                        self.cases[56]=Piece()
                        self.cases[59]=Piece('TOUR','blanc')

                    elif(arrivee==62):
                        self.cases[63]=Piece()
                        self.cases[61]=Piece('TOUR','blanc')

            # Black KING
            else:

                if(depart==4):
                    self.black_can_castle_0=False
                    self.black_can_castle_7=False

                    if(arrivee==6):
                        self.cases[7]=Piece()
                        self.cases[5]=Piece('TOUR','noir')

                    elif(arrivee==2):
                        self.cases[0]=Piece()
                        self.cases[3]=Piece('TOUR','noir')

        # End pieces cases-----------------------------------------------

        # Any move cancels the ep move
        if(flagViderEp==True):
            self.ep=-1

        # Promote : the pawn is changed to requested piece
        if(promote!=''):
            if(promote=='q'):
                self.cases[arrivee]=Piece('DAME',self.side2move)
            elif(promote=='r'):
                self.cases[arrivee]=Piece('TOUR',self.side2move)
            elif(promote=='n'):
                self.cases[arrivee]=Piece('CAVALIER',self.side2move)
            elif(promote=='b'):
                self.cases[arrivee]=Piece('FOU',self.side2move)

        # Change side to move
        self.changeTrait()

        # Save move to the history list
        self.history.append((depart,\
        arrivee,\
        pieceDeplacee,\
        piecePrise,\
        isEp,\
        histEp,\
        promote,\
        hist_roque_56,\
        hist_roque_63,\
        hist_roque_0,\
        hist_roque_7))

        # If the move lets king in check, undo it and return false
        if(self.in_check(self.oppColor(self.side2move))):
            self.undomove()
            return False

        return True



    def undomove(self):

        "Undo the last move in history"

        if(len(self.history)==0):
            print('No move played')
            return

        # The last move in history is : self.historique[-1]
        lastmove=self.history[-1]

        pos1=lastmove[0]
        pos2=lastmove[1]
        piece_deplacee=lastmove[2]
        piece_prise=lastmove[3]
        isEp=lastmove[4]
        ep=lastmove[5]
        promote=lastmove[6]
        self.white_can_castle_56=lastmove[7]
        self.white_can_castle_63=lastmove[8]
        self.black_can_castle_0=lastmove[9]
        self.black_can_castle_7 =lastmove[10]

        self.ply-=1

        # Change side to move
        self.changeTrait()

        # Replacing piece on square number 'pos1'
        self.cases[pos1]=self.cases[pos2]

        # Square where we can take "en pasant"
        self.ep=ep

        # If undoing a promote, the piece was a pawn
        if(promote!=''):
            self.cases[pos1]=Piece('PION',self.side2move)

        # Replacing capture piece on square 'pos2'
        self.cases[pos2]=piece_prise

        # Switch the piece we have replaced to 'pos1'-------------------
        if(self.cases[pos1].nom=='PION'):
            # If a pawn has been taken "en passant", replace it
            if(isEp):
                self.cases[pos2]=Piece()
                if(self.cases[pos1].couleur=='noir'):
                    self.cases[pos2-8]=Piece('PION','blanc')
                else:
                    self.cases[pos2+8]=Piece('PION','noir')

        # Replacing KING -----------------------------------------------
        elif(self.cases[pos1].nom=='ROI'):

            # White KING
            if(self.cases[pos1].couleur=='blanc'):
                # Replacing on initial square
                if(pos1==60):
                    # If the move was castle, replace ROOK
                    if(pos2==58):
                        self.cases[56]=Piece('TOUR','blanc')
                        self.cases[59]=Piece()
                    elif(pos2==62):
                        self.cases[63]=Piece('TOUR','blanc')
                        self.cases[61]=Piece()
            # Black KING
            else:
                if(pos1==4):
                    if(pos2==2):
                        self.cases[0]=Piece('TOUR','noir')
                        self.cases[3]=Piece()
                    elif(pos2==6):
                        self.cases[7]=Piece('TOUR','noir')
                        self.cases[5]=Piece()
        # End switch piece----------------------------------------------

        # Delete the last move from history
        self.history.pop()



    def changeTrait(self):

        "Change the side to move"

        if(self.side2move=='blanc'):
            self.side2move='noir'
        else:
            self.side2move='blanc'



    def oppColor(self,c):

        "Returns the opposite color of the 'c' color given"

        if(c=='blanc'):
            return 'noir'
        else:
            return 'blanc'



    def in_check(self,couleur):

        """Returns TRUE or FALSE
        if the KING of the given 'color' is in check"""

        # Looking for the id square where is the king
        # sure, we can code better to avoid this and win kn/s...
        for i in range(0,64):
            if(self.cases[i].nom=='ROI' and self.cases[i].couleur==couleur):
                pos=i
                break

        return self.is_attacked(pos,self.oppColor(couleur))



    def is_attacked(self,pos,couleur):

        """Returns TRUE or FALSE if the square number 'pos' is a
        destination square for the color 'couleur'.
        If so we can say that 'pos' is attacked by this side.
        This function is used for 'in check' and for castle moves."""

        mList=self.gen_moves_list(couleur,True)

        for pos1,pos2,promote in mList:
            if(pos2==pos):
                return True

        return False



    def render(self):

        "Display the chessboard in console mode"

        input("\nType a key to continue...")
        os.system('cls' if os.name == 'nt' else 'clear')

        print('')
        print('=> Commands are :')
        print('- "new" for a new game')
        print('- "e2e4" for example, to move a piece')
        print('- "e7e8q" for a promote move to queen ("r" for rook, "n" for knight, "b" for bishop)')
        print('- "legalmoves" show legal moves for side to move')
        print('- "undomove" to cancel the last move')
        print('- "go" asks the engine to play now')
        print('- "setboard [fen]" to set the board as the FEN notation given')
        print('- "getboard" to export the current FEN board position')
        print('- "sd [x]" to set the depth search')
        print('- "perft [x]" : test the move generator (x = search depth)')
        print('- "quit"... to quit')
        print('')

        print('8',end='   ')
        i,y=1,7
        for piece in self.cases:
            if(piece.couleur=='noir'):
                print(piece.nom[0].lower(),end='   ')
            else:
                print(piece.nom[0],end='   ')

            if(i%8==0):
                print()
                print()
                if(y>0):
                    print(str(y),end='   ')
                y=y-1

            i+=1
        print('    a   b   c   d   e   f   g   h')

        print('Side to move : '+self.side2move)

        if(self.ep!=-1):
            print('"en passant" possible in',self.coord[self.ep])

        # Displaying castle rights
        no_castle_right=True
        print('Castle rights : ',end='')
        if(self.white_can_castle_63):
            print('K',end='')
            no_castle_right=False
        if(self.white_can_castle_56):
            print('Q',end='')
            no_castle_right=False
        if(self.black_can_castle_7):
            print('k',end='')
            no_castle_right=False
        if(self.black_can_castle_0):
            print('q',end='')
            no_castle_right=False
        if(no_castle_right):
            print('-',end='')
        print()

        # Displaying moves done from the history
        self.showHistory()



    def caseStr2Int(self,c):

        """'c' given in argument is a square name like 'e2'
        "This functino returns a square number like 52"""

        err=(
        'The square name must be 2 caracters i.e. e2,e4,b1...',
        'Incorrect square name. Please enter i.e. e2,e4,b1...'
        )
        letters=('a','b','c','d','e','f','g','h')
        numbers=('1','2','3','4','5','6','7','8')

        if(len(c)!=2):
            print(err[0])
            return -1

        if(c[0] not in letters):
            print(err[1])
            return -1

        if(c[1] not in numbers):
            print(err[1])
            return -1

        return self.coord.index(c)



    def caseInt2Str(self,i):

        """Given in argument : an integer between 0 and 63
        Returns a string like 'e2'"""

        err=(
        'Square number must be in 0 to 63',
        )
        letters=('a','b','c','d','e','f','g','h')
        numbers=('1','2','3','4','5','6','7','8')

        if(i<0 or i>63):
            print(err[0])
            return

        return self.coord[i]



    @staticmethod
    def ROW(x):
        """ROW returns the number of the row from 0(a8-h8) to 7(a1-h1)
        in which is the square 'x'"""
        return (x >> 3)



    @staticmethod
    def COL(x):
        """COL returns the number of the colon (from 0 to 7)
        in which is the square 'x'"""
        return (x & 7)



    def showHistory(self):

        "Displays the history of the moves played"

        if(len(self.history)==0):
            return

        print()
        cpt,aff=1.0,True
        for (depart,\
        arrivee,\
        pieceDeplacee,\
        piecePrise,\
        isEp,\
        histEp,\
        promote,\
        roque56,\
        roque63,\
        roque0,\
        roque7) in self.history:
            a=self.caseInt2Str(depart)
            b=self.caseInt2Str(arrivee)
            if(piecePrise.isEmpty()==False):
                a=a+'x'
            if(promote!=''):
                b=b+promote
            if(aff==True):
                print("{}.{}{} ".format(int(cpt),a,b),end=' ')
                aff=False
            else:
                print("{}{} ".format(a,b),end=' ')
                aff=True
            cpt+=0.5
        print()
        print()



    def evaluer(self):

        """A wonderful evaluate() function
        returning actually only the material score"""

        WhiteScore=0
        BlackScore=0

        # Parsing the board squares from 0 to 63
        for pos1,piece in enumerate(self.cases):

            # Material score
            if(piece.couleur=='blanc'):
                WhiteScore+=piece.valeur
            else:
                # NB : here is for black piece or empty square
                BlackScore+=piece.valeur

        if(self.side2move=='blanc'):
            return WhiteScore-BlackScore
        else:
            return BlackScore-WhiteScore

"""#Engine"""

from piece import *
import time

class Engine:

    "The chess engine"



    def __init__(self):

        self.MAX_PLY=32
        self.pv_length=[0 for x in range(self.MAX_PLY)]
        self.INFINITY=32000
        self.init()



    def usermove(self,b,c):

        """Move a piece for the side to move, asked in command line.
        The command 'c' in argument is like 'e2e4' or 'b7b8q'.
        Argument 'b' is the chessboard.
        """

        if(self.endgame):
            self.print_result(b)
            return

        # Testing the command 'c'. Exit if incorrect.
        chk=self.chkCmd(c)
        if(chk!=''):
            print(chk)
            return

        # Convert cases names to int, ex : e3 -> 44
        pos1=b.caseStr2Int(c[0]+c[1])
        pos2=b.caseStr2Int(c[2]+c[3])

        # Promotion asked ?
        promote=''
        if(len(c)>4):
            promote=c[4]
            if(promote=='q'):
                promote='q'
            elif(promote=='r'):
                promote='r'
            elif(promote=='n'):
                promote='n'
            elif(promote=='b'):
                promote='b'

        # Generate moves list to check
        # if the given move (pos1,pos2,promote) is correct
        mList=b.gen_moves_list()

        # The move is not in list ? or let the king in check ?
        if(((pos1,pos2,promote) not in mList) or \
        (b.domove(pos1,pos2,promote)==False)):
            print("\n"+c+' : incorrect move or let king in check'+"\n")
            return

        # Display the chess board
        b.render()

        # Check if game is over
        self.print_result(b)

        # Let the engine play
        #self.search(b)



    def chkCmd(self,c):

        """Check if the command 'c' typed by user is like a move,
        i.e. 'e2e4','b7b8n'...
        Returns '' if correct.
        Returns a string error if not.
        """

        err=(
        'The move must be 4 or 5 letters : e2e4, b1c3, e7e8q...',
        'Incorrect move.'
        )
        letters=('a','b','c','d','e','f','g','h')
        numbers=('1','2','3','4','5','6','7','8')

        if(len(c)<4 or len(c)>5):
            return err[0]

        if(c[0] not in letters):
            return err[1]

        if(c[1] not in numbers):
            return err[1]

        if(c[2] not in letters):
            return err[1]

        if(c[3] not in numbers):
            return err[1]

        return ''



    def search(self,b):

        """Search the best move for the side to move,
        according to the given chessboard 'b'
        """

        if(self.endgame):
            self.print_result(b)
            return

        # TODO
        # search in opening book

        self.clear_pv()
        self.nodes=0
        b.ply=0

        print("ply\tnodes\tscore\tpv")

        for i in range(1,self.init_depth+1):

            score=self.alphabeta(i,-self.INFINITY,self.INFINITY,b)

            print("{}\t{}\t{}\t".format(i,self.nodes,score/10),end='')

            # print PV informations : ply, nodes...
            j=0
            while(self.pv[j][j]!=0):
                c=self.pv[j][j]
                pos1=b.caseInt2Str(c[0])
                pos2=b.caseInt2Str(c[1])
                print("{}{}{}".format(pos1,pos2,c[2]),end=' ')
                j+=1
            print()

            # Break if MAT is found
            if(score>self.INFINITY-100 or score<-self.INFINITY+100):
                break

        # root best move found, do it, and print result
        best=self.pv[0][0]
        b.domove(best[0],best[1],best[2])
        self.print_result(b)



    def alphabeta(self,depth,alpha,beta,b):

        # We arrived at the end of the search : return the board score
        if(depth==0):
            return b.evaluer()
            # TODO : return quiesce(alpha,beta)

        self.nodes+=1
        self.pv_length[b.ply] = b.ply

        # Do not go too deep
        if(b.ply >= self.MAX_PLY-1):
            return b.evaluer()

        # Extensions
        # If king is in check, let's go deeper
        chk=b.in_check(b.side2move) # 'chk' used at the end of func too
        if(chk):
            depth+=1

        # TODO
        # sort moves : captures first

        # Generate all moves for the side to move. Those who
        # let king in check will be processed in domove()
        mList=b.gen_moves_list()

        f=False # flag to know if at least one move will be done
        for i,m in enumerate(mList):

            # Do the move 'm'.
            # If it lets king in check, undo it and ignore it
            # remind : a move is defined with (pos1,pos2,promote)
            # i.e. : 'e7e8q' is (12,4,'q')
            if(not b.domove(m[0],m[1],m[2])):
                continue

            f=True # a move has passed

            score=-self.alphabeta(depth-1,-beta,-alpha,b)

            # Unmake move
            b.undomove()

            if(score>alpha):

                # TODO
                # this move caused a cutoff,
                # should be ordered higher for the next search

                if(score>=beta):
                    return beta
                alpha = score

                # Updating the triangular PV-Table
                self.pv[b.ply][b.ply] = m
                j = b.ply + 1
                while(j<self.pv_length[b.ply+1]):
                    self.pv[b.ply][j] = self.pv[b.ply+1][j]
                    self.pv_length[b.ply] = self.pv_length[b.ply + 1]
                    j+=1

        # If no move has been done : it is DRAW or MAT
        if(not f):
            if(chk):
                return -self.INFINITY + b.ply # MAT
            else:
                return 0 # DRAW

        # TODO
        # 50 moves rule

        return alpha



    def print_result(self,b):

        "Check if the game is over and print the result"

        # Is there at least one legal move left ?
        f=False
        for pos1,pos2,promote in b.gen_moves_list():
            if(b.domove(pos1,pos2,promote)):
                b.undomove()
                f=True # yes, a move can be done
                break

        # No legal move left, print result
        if(not f):
            if(b.in_check(b.side2move)):
                if(b.side2move=='blanc'):
                    print("0-1 {Black mates}")
                else:
                    print("1-0 {White mates}")
            else:
                print("1/2-1/2 {Stalemate}")
            self.endgame=True

        # TODO
        # 3 reps
        # 50 moves rule



    def clear_pv(self):

        "Clear the triangular PV table containing best moves lines"

        self.pv=[[0 for x in range(self.MAX_PLY)] for x in range(self.MAX_PLY)]



    def setboard(self,b,c):

        """Set the chessboard to the FEN position given by user with
        the command line 'setboard ...'.
        'c' in argument is for example :
        'setboard 8/5k2/5P2/8/8/5K2/8/8 w - - 0 0'
        """

        cmd=c.split() # split command with spaces
        cmd.pop(0) # drop the word 'setboard' written by user

        # set the FEN position on board
        if(b.setboard(' '.join(cmd))):
            self.endgame=False # success, so no endgame



    def setDepth(self,c):

        """'c' is the user command line, i.e. 'sd [x]'
        to set the search depth.
        """

        # Checking the requested value
        cmd=c.split()
        #cmd[0]='sd'
        #cmd[1] should be an integer

        try:
            d=int(cmd[1])
        except ValueError:
            print('Depth isn\'t an integer. Please type i.e. : sd 5')
            return

        if(d<2 or d>self.MAX_PLY):
            print('Depth must be between 2 and',self.MAX_PLY)
            return

        # Things seems to be all right
        self.init_depth=d
        print('Depth set to',d)



    def perft(self,c,b):

        """PERFformance Test :
        This is a debugging function through the move generation tree
        for the current board until depth [x].
        'c' is the command line written by user : perft [x]
        """

        # Checking the requested depth
        cmd=c.split()
        #cmd[0]='perft'

        try:
            d=int(cmd[1])
        except ValueError:
            print('Please type an integer as depth i.e. : perft 5')
            return

        if(d<1 or d>self.MAX_PLY):
            print('Depth must be between 1 and',self.MAX_PLY)
            return

        print("Depth\tNodes\tCaptures\tE.p.\tCastles\tPromotions\tChecks\tCheckmates")

        time1 = self.get_ms()
        for i in range(1,d+1):
            total=self.perftoption(0,i-1,b)
            print("{}\t{}".format(i,total))
        time2 = self.get_ms()
        timeDiff = round((time2-time1)/1000,2)
        print('Done in',timeDiff,'s')

    def perftoption(self,prof,limit,b):
        cpt=0

        if(prof>limit):
            return 0

        l=b.gen_moves_list()

        for i,m in enumerate(l):

            if(not b.domove(m[0],m[1],m[2])):
                continue

            cpt+=self.perftoption(prof+1,limit,b)

            if(limit==prof):
                cpt+=1

            b.undomove()

        return cpt



    def legalmoves(self,b):

        "Show legal moves for side to move"

        mList=b.gen_moves_list()

        cpt=1
        for m in mList:
            if(not b.domove(m[0],m[1],m[2])):
                continue
            print('move #',cpt,':',b.caseInt2Str(m[0])+b.caseInt2Str(m[1])+m[2])
            b.undomove()
            cpt+=1



    def getboard(self,b):

        """The user requests the current FEN position
        with the command 'getboard'"""

        print(b.getboard())



    def newgame(self,b):

        self.init()
        b.init()



    def bench(self,b):

        """Test to calculate the number of nodes a second.
        The position used is the 17th move of the game :
        Bobby Fischer vs. J. Sherwin, New Jersey State
        Open Championship, 9/2/1957 :
        1rb2rk1/p4ppp/1p1qp1n1/3n2N1/2pP4/2P3P1/PPQ2PBP/R1B1R1K1 w - - 0 1
        The engine searches to a given depth, 3 following times.
        The kilonodes/s is calculated with the best time.
        """

        oldDepth=self.init_depth
        self.init_depth=4
        timeDiff=[]

        # testing 3 times
        for i in range(3):

            print('Searching to depth',self.init_depth,'...')

            if(not b.setboard('1rb2rk1/p4ppp/1p1qp1n1/3n2N1/2pP4/2P3P1/PPQ2PBP/R1B1R1K1 w - - 0 1')):
                print('Could not set board ???!#!')
                return

            start_time=self.get_ms()
            self.search(b)
            stop_time=self.get_ms()
            timeDiff.append(stop_time-start_time)
            print('Time:',timeDiff[i],'ms\n')

        if(timeDiff[1] < timeDiff[0]):
            timeDiff[0] = timeDiff[1]
        if(timeDiff[2] < timeDiff[0]):
            timeDiff[0] = timeDiff[2]

        print('Best time:',timeDiff[0],'ms')
        print('Nodes:',self.nodes)
        print('Nodes per second:',round(self.nodes/timeDiff[0],2),'kn/s')

        # Restoring changed values
        self.init_depth=oldDepth



    def undomove(self,b):

        "The user requested a 'undomove' in command line"

        b.undomove()
        self.endgame=False



    def get_ms(self):
        return int(round(time.time() * 1000))



    def init(self):
        self.endgame=False
        self.init_depth=4 # search in fixed depth
        self.nodes=0 # number of nodes
        self.clear_pv()

"""#Main"""

#!/usr/bin/env python3

from board import *
from engine import *

b=Board()
e=Engine()

while(True):

    b.render()

    c=input('>>> ')

    if(c=='quit' or c=='exit'):
        exit(0)

    elif(c=='undomove'):
        e.undomove(b)

    elif('setboard' in c):
        e.setboard(b,c)

    elif(c=='getboard'):
        e.getboard(b)

    elif(c=='go'):
        e.search(b)

    elif(c=='new'):
        e.newgame(b)

    elif(c=='bench'):
        e.bench(b)

    elif('sd ' in c):
        e.setDepth(c)

    elif('perft ' in c):
        e.perft(c,b)

    elif(c=='legalmoves'):
        e.legalmoves(b)

    else:
        # coup à jouer ? ex : e2e4
        e.usermove(b,c)