# -*- coding: utf-8 -*-
"""mctsChess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j45UD6Djo_5dH8YIK8MICG6lFYYnUalM

#mctsChess
 Board, Piece, Engine, et la classe Main qui intègre un moteur de jeu avec apprentissage par renforcement et recherche d'arbre Monte Carlo (MCTS). Cette implémentation se concentre sur la structure de base et sur l'architecture du moteur de jeu, mais elle peut nécessiter des améliorations pour une version plus avancée et réaliste.

 ## Explications des principales fonctionnalités :
1. Board : Représente l'échiquier, initialise les pièces et gère les mouvements.
2. Piece : Représente une pièce individuelle sur l'échiquier.
3. Engine : Gère l'algorithme MCTS. Chaque Node représente un état du jeu, et l'arbre MCTS explore les coups possibles pour choisir le meilleur coup.
4. Main : La classe principale qui gère le déroulement du jeu, en alternant entre les joueurs et en utilisant l'algorithme MCTS pour choisir les coups.
## Améliorations possibles :
* Implémenter une vraie logique de validation des mouvements selon les règles des échecs.
* Améliorer la fonction d'évaluation des positions pour rendre l'apprentissage par renforcement plus robuste.
* Ajouter une gestion plus précise des conditions de victoire ou de match nul.
Ce code présente une structure de base pour un moteur d'échecs utilisant MCTS et l'apprentissage par renforcement, mais beaucoup d'aspects peuvent être enrichis pour un jeu complet et performant.

#Piece
Piece est responsable de la représentation d'une piece individuelle.
"""

class Piece:
    def __init__(self, color, name):
        self.color = color  # 'white' or 'black'
        self.name = name  # 'king', 'queen', 'rook', etc.

    def __str__(self):
        return f'{self.color[0].upper()}{self.name[0].upper()}'

    def __repr__(self):
        return self.__str__()

"""#Board
Board est responsable de la représentation de l'échiquier et des mouvements des pièces.
"""

class Board:
    def __init__(self):
        self.board = [[None for _ in range(8)] for _ in range(8)]  # 8x8 board

        # Initialisation des pièces (simplifiée ici)
        self.setup_board()

    def setup_board(self):
        # Mettre en place les pièces pour les deux joueurs
        # Rook, Knight, Bishop, Queen, King, Bishop, Knight, Rook
        for i in range(8):
            self.board[0][i] = Piece('black', ['rook', 'knight', 'bishop', 'queen', 'king', 'bishop', 'knight', 'rook'][i])
            self.board[1][i] = Piece('black', 'pawn')
            self.board[6][i] = Piece('white', 'pawn')
            self.board[7][i] = Piece('white', ['rook', 'knight', 'bishop', 'queen', 'king', 'bishop', 'knight', 'rook'][i])

    def display(self):
        # Afficher l'échiquier
        for row in self.board:
            print(" ".join([str(piece) if piece else "." for piece in row]))

    def is_valid_move(self, start, end):
        # Fonction de validation simplifiée
        return True

    def move(self, start, end):
        # Déplacer une pièce sur l'échiquier
        piece = self.board[start[0]][start[1]]
        self.board[end[0]][end[1]] = piece
        self.board[start[0]][start[1]] = None

"""#Engine
 Engine (Moteur de jeu avec MCTS et apprentissage par renforcement)
L'Engine gère la logique du jeu, le moteur Monte Carlo et l'intégration de l'apprentissage par renforcement.
"""

import random

class Node:
    def __init__(self, board, parent=None, move=None):
        self.board = board  # L'état du jeu à ce point
        self.parent = parent  # Le parent dans l'arbre
        self.move = move  # Le mouvement qui a mené à cet état
        self.children = []  # Enfants de ce noeud (états futurs possibles)
        self.visits = 0  # Nombre de fois que ce noeud a été exploré
        self.value = 0  # La valeur (récompense) associée à ce noeud

    def is_fully_expanded(self):
        # Vérifie si tous les enfants de ce noeud ont été générés
        return len(self.children) > 0

    def best_child(self, exploration_weight=1.41):
        # Choisit le meilleur enfant en fonction de l'UCT (Upper Confidence Bound for Trees)
        best_value = -float('inf')
        best_move = None
        for child in self.children:
            uct_value = child.value / (child.visits + 1e-6) + exploration_weight * (child.visits ** 0.5)
            if uct_value > best_value:
                best_value = uct_value
                best_move = child
        return best_move

class Engine:
    def __init__(self, board):
        self.board = board
        self.root_node = Node(board)

    def selection(self):
        node = self.root_node
        while node.is_fully_expanded():
            node = node.best_child()
        return node

    def expansion(self, node):
        # Générer les nouveaux noeuds (les mouvements possibles)
        for move in self.generate_legal_moves(node.board):
            new_board = self.simulate_move(node.board, move)
            child_node = Node(new_board, parent=node, move=move)
            node.children.append(child_node)

    def simulation(self, node):
        # Effectuer une simulation jusqu'à un état terminal
        board = node.board
        while not self.is_game_over(board):
            move = random.choice(self.generate_legal_moves(board))
            board = self.simulate_move(board, move)
        return self.evaluate_board(board)

    def backpropagation(self, node, reward):
        # Propager la récompense en remontant l'arbre
        while node:
            node.visits += 1
            node.value += reward
            node = node.parent

    def generate_legal_moves(self, board):
        # Générer tous les mouvements légaux à partir d'un état donné (simplifié ici)
        return [(x, y) for x in range(8) for y in range(8)]

    def simulate_move(self, board, move):
        # Appliquer un mouvement et renvoyer le nouvel état du jeu
        new_board = [row[:] for row in board]  # Faire une copie de l'échiquier
        x, y = move
        new_board[x][y] = board[x][y]  # Mouvement simplifié
        return new_board

    def is_game_over(self, board):
        # Vérifie si le jeu est terminé (simplifié ici)
        return False

    def evaluate_board(self, board):
        # Évaluation d'une position du jeu (simplifié)
        return random.uniform(-1, 1)  # Une récompense aléatoire pour l'exemple

    def mcts(self, iterations=1000):
        for _ in range(iterations):
            node = self.selection()
            self.expansion(node)
            reward = self.simulation(node)
            self.backpropagation(node, reward)

        # Retourner le meilleur mouvement après les itérations
        best_move = self.root_node.best_child(0)
        return best_move.move

"""#Main
Main (exécution du jeu)

"""

#La classe principale pour gérer l'exécution du jeu, incluant le tour des joueurs et l'interaction avec le moteur MCTS.

class Main:
    def __init__(self):
        self.board = Board()
        self.engine = Engine(self.board.board)
        self.current_player = 'white'

    def play(self):
        while True:
            self.board.display()
            if self.current_player == 'white':
                print("C'est au tour des blancs.")
            else:
                print("C'est au tour des noirs.")

            move = self.engine.mcts()  # Utiliser MCTS pour choisir le meilleur mouvement
            print(f"Le mouvement choisi est: {move}")
            self.board.move(move[0], move[1])

            if self.is_game_over():
                print(f"{self.current_player} a gagné !")
                break

            self.current_player = 'black' if self.current_player == 'white' else 'white'

    def is_game_over(self):
        # Vérifier la condition de fin de jeu (simplifié ici)
        return False

if __name__ == "__main__":
    game = Main()
    game.play()

"""#Main IA
Pour que l'un des joueurs soit un moteur IA (comme un moteur MCTS), nous devons ajuster la classe Main afin de permettre au moteur IA de jouer automatiquement pendant que l'autre joueur contrôle manuellement ou joue autrement.

Voici comment vous pourriez structurer la classe Main avec un joueur humain et un joueur IA utilisant MCTS. L'idée est que le joueur humain pourrait entrer ses coups manuellement, tandis que l'IA choisira ses coups via l'algorithme MCTS.

1. Modifications dans la classe Main
Nous allons ajouter une option pour que l'un des joueurs soit un humain et l'autre un moteur IA. Voici un exemple avec un joueur humain jouant les blancs et l'IA jouant les noirs.
"""

class Main:
    def __init__(self, human_player='white'):
        self.board = Board()
        self.engine = Engine(self.board.board)
        self.current_player = 'white'
        self.human_player = human_player  # Le joueur humain (blanc ou noir)

    def play(self):
        while True:
            self.board.display()
            if self.current_player == 'white':
                if self.current_player == self.human_player:
                    print("C'est au tour des blancs (Joueur Humain).")
                    move = self.get_human_move()
                else:
                    print("C'est au tour des blancs (IA).")
                    move = self.engine.mcts()  # Moteur IA pour les blancs
            else:
                if self.current_player == self.human_player:
                    print("C'est au tour des noirs (Joueur Humain).")
                    move = self.get_human_move()
                else:
                    print("C'est au tour des noirs (IA).")
                    move = self.engine.mcts()  # Moteur IA pour les noirs

            print(f"Le mouvement choisi est: {move}")
            self.board.move(move[0], move[1])

            if self.is_game_over():
                print(f"{self.current_player} a gagné !")
                break

            self.current_player = 'black' if self.current_player == 'white' else 'white'

    def get_human_move(self):
        """
        Permet à l'utilisateur humain de saisir un mouvement sous la forme (ligne, colonne) par exemple (6, 4) pour déplacer une pièce.
        Cette fonction peut être améliorée pour accepter des mouvements comme 'e2 e4' au lieu de coordonnées.
        """
        while True:
            move_input = input("Entrez votre mouvement sous la forme 'x1 y1 x2 y2' (ex : 6 4 4 4) : ")
            try:
                start_x, start_y, end_x, end_y = map(int, move_input.split())
                if self.board.is_valid_move((start_x, start_y), (end_x, end_y)):
                    return (start_x, start_y), (end_x, end_y)
                else:
                    print("Mouvement invalide, essayez encore.")
            except ValueError:
                print("Format de mouvement invalide. Essayez encore.")

    def is_game_over(self):
        """
        Vérifie si la partie est terminée (simplifié pour le moment).
        """
        return False  # À remplacer par une logique de fin de jeu réelle (vérification de la victoire ou du match nul)

if __name__ == "__main__":
    # Joueur humain joue avec les blancs, IA joue avec les noirs
    game = Main(human_player='white')
    game.play()

"""## Explications des changements :
1. Attribut human_player : Cet attribut détermine quel joueur est humain ('white' ou 'black'). Le joueur humain peut ainsi être soit les blancs, soit les noirs. L'autre joueur sera géré par l'IA.

2. Mouvement humain (méthode get_human_move) :

* Cette méthode demande à l'utilisateur d'entrer un mouvement sous la forme (x1, y1, x2, y2) (coordonnées de départ et d'arrivée).
* La méthode vérifie que le mouvement est valide avec la fonction is_valid_move() de la classe Board.
3. Choix du mouvement de l'IA :

* Si le joueur est un humain, le mouvement est obtenu via get_human_move().
* Si le joueur est une IA, le moteur MCTS est utilisé pour choisir le meilleur coup via self.engine.mcts().
4. Tour des joueurs :

* Le jeu alterne entre les tours du joueur humain et de l'IA. Si c'est le tour de l'humain, il doit entrer un coup, et si c'est l'IA, le moteur MCTS génère un coup automatiquement.
5. Fin de la partie :

* La condition de fin de jeu est simplifiée ici. Vous devrez implémenter des vérifications plus détaillées dans is_game_over() pour déterminer la victoire ou le match nul.
## Exemple d'utilisation
Lorsque vous exécutez le code, si vous jouez contre l'IA, vous pourrez entrer vos coups manuellement, tandis que l'IA jouera ses coups automatiquement en utilisant l'algorithme MCTS. Par exemple, l'utilisateur pourrait entrer un coup comme :

arduino
Copier le code
Entrez votre mouvement sous la forme 'x1 y1 x2 y2' (ex : 6 4 4 4) : 6 4 4 4
L'IA répondra avec un coup basé sur le moteur MCTS.

## Améliorations possibles :
* Validation des mouvements : La méthode is_valid_move dans Board doit être étendue pour valider les mouvements selon les règles réelles des échecs (par exemple, en prenant en compte les déplacements des pièces).
* Gestion de la fin de partie : Vous pouvez améliorer is_game_over pour vérifier les conditions de victoire comme l'échec et mat, ou un match nul (par exemple, stalemate, pat, etc.).
* Affichage des coups : Vous pouvez également améliorer l'affichage des coups de manière plus conviviale, par exemple en permettant à l'utilisateur de saisir des coups sous forme de notation algébrique (e2 e4).
"""